<?php

/**
 * Implements hook_block_view
 */
function blocks_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'block_header':
            $block['subject'] = NULL;
            $block['content'] = theme('block_header', array('items' => blocks_view_header()));
            return $block;
            break;
    }
}

/**
 * Implements hook_block_info().
 */
function blocks_block_info() {
    $blocks['block_header'] = array(
        'info' => t('block header'),
        'cache' => DRUPAL_NO_CACHE,
        'region' => 'header',
    );

    return $blocks;
}

/**
 * Implements hook_theme
 */
function blocks_theme() {
    return array(
        'block_header' => array(
            'template' => '/tpl/block_header',
            'render element' => 'content',
            'variables' => array(
                '#items' => NULL,
            ),
        ),
    );
}

/**
 * Add function blocks_view_main_menu()
 * 
 * To view block main menu
 */
function blocks_view_header() {
    $menu = menu_tree('main-menu');
    $return = array();
    $current_path = current_path();
    foreach ($menu as $item) {
        if (isset($item['#title']) && isset($item['#href'])) {
            $return[] = array(
                'title' => $item['#title'],
                'href' => url($item['#href']),
                'class' => ($item['#href'] == $current_path || ( $item['#href'] == '<front>' && drupal_is_front_page() == TRUE)) ? 'active' : '',
            );
        }
    }
    return $return;
}   
